### ISSUE TITLE
Improve handling when no votes exist for a snap

### ISSUE THREAD

**Issue by tim-hm** [ubuntu/app-center-ratings#59]
The call to get app ratings returns an internal server error if there are no votes for the specific snap_id. This is caused by using `fetch_one` in [get_votes_by_snap_id](https://github.com/ubuntu/app-center-ratings/blob/62c4563a3ff71be7f25f1fd53cae22f6bab939d2/src/features/app/infrastructure.rs#L34) which throws  sqlx::RowNotFound if no votes are in the database.

**Comment by ZoopOTheGoop** [comment]
This was fixed in https://github.com/ubuntu/app-center-ratings/commit/35aa0dfb
