### ISSUE TITLE
ci: Revisit use of actions-rs due to upstream deprecation

### ISSUE THREAD

**Issue by tim-hm** [ubuntu/app-center-ratings#79]
actions-rs is without a maintainer and so we will need to consider our options. 

Ref: https://github.com/actions-rs/meta/issues/43

Edit by Zoe:

Tasks:
- [ ] Find an alternative to `rust-toolchain`
- [x] Find an alternative to `clippy`

**Comment by ZoopOTheGoop** [comment]
Alternatives that are maintained:
https://github.com/orgs/crusty-pie/repositories
https://github.com/dtolnay/rust-toolchain

We have also successfully replaced the clippy action already.
